executor: slurm
jobs: 30

printshellcmds: true
verbose: false
latency-wait: 60
max-jobs-per-second: 5
jobname: "smk-{rulename}-{jobid}"

software-deployment-method: ["apptainer"]
apptainer-args: >-
  --bind /home/PERSONALE/alessandro.fuschi2:/home/PERSONALE/alessandro.fuschi2
  --bind /scratch:/scratch
  --bind /archive:/archive
  --cleanenv

default-resources:
  - slurm_account=applicata
  - slurm_qos=normal
  - cpus-per-task=1
  - runtime=30
  - mem_mb=2000
  - slurm_requeue=false

slurm-logdir: "workflow/work/logs/slurm"
slurm-keep-successful-logs: false
